### PR TITLE
Support userAgent specified in testEnvironmentOptions

### LINKED ISSUE #3: Can't pass userAgent to testEnvironmentOptions
I was trying to add `testEnvironmentOptions.userAgent`, following Jest docs: https://jestjs.io/docs/en/configuration#testenvironmentoptions-object

But, when using `jest-environment-jsdom-fifteen`, it doesn't work.

Looks like since v12, `jsdom` requires that a resource loader is passed to the jsdom constructor options for advanced configuration like that: https://github.com/jsdom/jsdom#advanced-configuration

### PR DESCRIPTION
**Pull request by diegohaz**
Closes #3

### CODE REVIEW

**Comment by ianschmitz** [comment]
Hi @diegohaz - thanks for the PR. Have you confirmed that this change fixes the issue as described in #3?

**Comment by diegohaz** [comment]
@ianschmitz Yes! I'm currently using [`patch-package`](https://github.com/ds300/patch-package) with these changes to make it work.

**Comment by ianschmitz** [comment]
Great. Thanks for the fix! I'll add tests in a follow-up PR and release shortly.

**Comment by ianschmitz** [comment]
Should be all fixed in `1.0.1`.

**Comment by diegohaz** [comment]
Thanks! :)

**Pull request merged**
